### ISSUE TITLE
Payment Calculator: Phone and Fax Fields

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#102]
For Customer info, Principal Info and Bank Reference: can the phone a fax numbers automatically show as "(507) 456-7898" when you type it in vs. showing up in different styles like they currently are?

**Comment by tbstevens** [comment]
@olegforce - Could you modify the credit application page to standardize the field to include the mask of (999) 999-9999 for phone and fax?

**Comment by tbstevens** [comment]
@OlegForce - The formatting is correct on both fields. However, the fax field is giving an error message stating "Please enter only digits". Only digits were entered so I'm assuming it is just a piece of validation that needs to be removed since the mask contains characters other than digits. Doesn't appear to be an issue on the phone field.

**Comment by OlegForce** [comment]
ooops. should work now
