### ISSUE TITLE
Sales Managers Add/Edit their Sales Reps?

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#105]
How are Vendor Sales Managers able to Add/Remove/Manage their Sales Reps on the site?

**Comment by tbstevens** [comment]
@Creekridge - I believe the enhancement request was for a separate role "Site Admin" to have that ability, not a Sales Manager. However, it is another planned topic for Thursday. Without pretty significant modifications to Liferay, Site level users are not permitted to add users to the portal. They are only permitted to add an already created user to their site. The user could be added one of two ways: 

1. User registers themselves (if you turn this feature on, a user can create their own account but would not belong to any sites until an administrator assigns them to a site). 
2. Portal Admin adds the user. Portal admins could add the user and assign them to a site during the same step.

There is one drawback to option 1. When users register themselves, they are registering to a general pool of users that belong to the overall portal. Site Admins have visibility to all users across the portal and can assign them to the site.

Option 2 would prevent that if you don't allow self registration.

In order to provide Site Admins the ability to actually add a new user that is not yet created in the portal to their own specific site is the function that would require significant customizations that we can walk through on Thursday.

**Comment by tbstevens** [comment]
Closed -- added as topic for meeting on 1/8
