### ISSUE TITLE
Auto-Save Inputted Information

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#114]
As we are testing, we're finding that some users aren't hitting the "save" button and getting frustrated to need to re-input data. Can we have it auto-save once they leave the page?

**Comment by tbstevens** [comment]
@Creekridge - I'll work with our developer to determine what the best options are for autosave. There isn't an easy mechanism for saving when a user takes action outside of the form itself, but we can look into ways to potentially have the form save each time a field moves focus (tab out, mouse out, etc). Because this could be a bigger change, I'll get an estimate from them to make sure we want to proceed.

**Comment by Creekridge** [comment]
@tbstevens could we just start with having it save when we hit "manage documents"?

**Comment by tbstevens** [comment]
@Creekridge - If you would prefer for this to just be logged as a defect to save when pressing manage docs, we can do that.

**Comment by Creekridge** [comment]
@tbstevens yes, please do that. Let's discuss auto-save tomorrow.

**Comment by tbstevens** [comment]
@creekridge - I believe this is still an open item. One of the downsides to saving on tab or on click of new section was related to going through validation before the save. Our recommendation would be to require save and it will now be saving on click of "Manage Documents" (once we deploy again). Let me know.

**Comment by tbstevens** [comment]
Closing issue.
