### ISSUE TITLE
CSS Field

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#119]
Can we make the CSS field bigger for admins?

**Comment by tbstevens** [comment]
@Creekridge - The CSS field is a control panel screen provided out of the box by Liferay. To modify this screen would require additional customization. We can look into this if desired. Alternatively, all textareas in Chrome are rendered with a resizable drag option to make the textarea larger on any screen. Otherwise, what I had been doing is simply copying the content, modifying it in a CSS editor, and then pasting the content back in.

**Comment by tbstevens** [comment]
@creekridge - Hi Sandy and Megan -- I'm not sure if you wanted to move forward on this one. We can have this expand to a larger textarea if you'd like. The estimate to customize this liferay screen is 2 hours. If not, I'll just close this one out.

**Comment by Creekridge** [comment]
Close it out

Sandy Graves
IT Manager
O: 952.826.7884
F: 952.996.0270
Sgraves@creekridgecapital.com<mailto:Sgraves@creekridgecapital.com>
www.creekridgecapital.com<http://www.creekridgecapital.com/>

[CreekridgeCapital_Standard_Color.jpg]





This email message is for the sole use of the intended recipients and may contain privileged and confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Although this email and any attachments are believed to be free of any virus or other defect, which might affect any system into which it is received or opened, it is the responsibility of the recipient to ensure that it is free from virus. The Sender and his/her employer accept no responsibility for any loss or damage arising in any way from its use.
