### ISSUE TITLE
Doc gen taking a long time to generate docs

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#133]
Issue
----------
Sometimes it can take over 15 seconds for a credit app or proposal letter document to generate. User doesn't know if they are waiting or if it didn't work.

Expected
---------------
Improve the performance/speed of generating the documents if possible.

**Comment by divinami** [comment]
@tbstevens Can you check if you see any of these messages in the logs:

04:10:23,814 INFO  [http-bio-8080-exec-5][SocketOpenOfficeConnection:125] trying to (re)connect
04:10:23,924 INFO  [http-bio-8080-exec-5][SocketOpenOfficeConnection:125] connected

This is the only time I noticed it taking a while longer to generate.  Otherwise, the credit app and proposal documents were generating in a couple of seconds.

**Comment by tbstevens** [comment]
Closing - will be part of request with other manage docs changes.
