### ISSUE TITLE
Payment Calculator Save & Exit

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#145]
This buttons should go directly to the "View Applications" page. For some reason, I was seeing an older version of the "View Applications" page when I click this button.

**Comment by tbstevens** [comment]
@Creekridge - I'll try and recreate the issue. It may have been due to a cache issue since I had to change the portlet for the View Applications page. If it was not a cache issue, I'll look into it. If you'd like to check, you could either clear the browsing history on the browser you're using, use a different browser not yet used, or open chrome in incognito mode which would not use any prior cache.

**Comment by tbstevens** [comment]
@OlegForce - I was able to recreate this same issue. It looks like the problem may be that the payment calculator save & exit button isn't just simply sending the user to the View Applications page URL which has the new portlet, but something different that is still displaying the old View applications portlet.

**Comment by Creekridge** [comment]
@tbstevens looks like this issue is fixed. Thanks.
