### ISSUE TITLE
Site Specific Login not showing login fields

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#161]
When I go to a Site specific login screen (ex: www.vendorservicesgroup.com/group/vendor1), the username and password fields are not available.

**Comment by tbstevens** [comment]
@creekridge - The step of setting up the one public page with the Vendor Login template was missed. It has since been added.

Just for future reference, after creating a new vendor site by using the "Vendor Site" Template for the private pages in the site, I created a one page template titled "Login" that can be added to all vendor sites as the one public page. I'll include this in a document.

**Comment by Creekridge** [comment]
Confirmed.  Now receive login fields when go to Vendor Site login.
