### ISSUE TITLE
New Vendor Login Page Showing Logo and Text

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#171]
@tbstevens when creating a new vendor login page, we are seeing both the LeaseStation logo and the text "LeaseStation". Can we have it just show the logo.  www.vendorservicesgroup.com/web/leasestation

**Comment by tbstevens** [comment]
@Creekridge - Updated the Vendor Login template to not show the site name in the banner. Also update the Lease Station site to now show the name since the Vendor Login template wasn't set right when the site was created. Future sites using that template will default to not show the site name.

For future reference, it's a checkbox that appears in the Logo screen of the Site Settings. Here's a screenshot.
https://www.dropbox.com/s/szvl5amtrjil7wa/ShowSiteName.png?dl=0

**Comment by Creekridge** [comment]
Thank you!
