### ISSUE TITLE
URL Links of Vendor Login Pages

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#172]
@tbstevens, what is the reasoning behind the "/web" being in the URL's? Is that something LifeRay does? Would it be possible to remove this from the URL's? If so, what is the time estimate of it?

**Comment by tbstevens** [comment]
@Creekridge - No estimate needed. Under site settings, you can set a Virtual Host domain on the public page or private page. Since you have redirect setup from the public page you could setup just the public page setting. As an example, I set it up on Vendor 1. If you go to vendor1.vendorservicesgroup.com it will take you to the public page for Vendor 1. If you go to Control Panel > Admin > Sites > Vendor 1 > Site Settings > Site URL -- you'll see the virtual host subdomain I setup.

**Comment by tbstevens** [comment]
@Creekridge - Adding to what I wrote earlier, virtual host option is what you can use if you wanted to set up a short subdomain for each vendor to remove the longer URL. As far as removing the "/web" for public pages and the "/group" for private pages, it's a little more complex. They cannot be removed unless you mapped to a virtual host as suggested earlier. There is an option to customize the url across the entire portal in the portal-ext.properties file that is in the liferay root folder.

The default values in the system are listed down below. You could modify those values to be different from "/web" or "/group" but you can't make them blank. The system wouldn't know if it is directing to a public or private page.

layout.friendly.url.private.group.servlet.mapping=/group
layout.friendly.url.public.servlet.mapping=/web

**Comment by Creekridge** [comment]
@tbstevens - with the virtual subdomain, this would mean we'd need a "wildcard" SSL certificate - correct?
