### ISSUE TITLE
Need another Custom Field

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#182]
@tbstevens - We need another custom field added - Provider Name.  This will be used in the documents and in some of the places that you currently have "Name" field loaded - like the Terms & Agreement popup.  In the case of the new site we set up, our Vendor is Homecare Homebase, but we are still Creekridge Capital LLC.  We can't have multiple sites labeled Creekridge Capital - that just causes additional confusion.

**Comment by tbstevens** [comment]
@Creekridge - We can add another custom field without more definition needed. However, it sounds like you have specific places where the code needs to be modified to pull in this new Provider name value instead of the site name. To better understand the effort, could you provide: 1. the screens/areas of the application where the name will need to be updated to use the new provider name field vs site name and any other business rules desired? My assumption is that you'll only want the value from the custom field "provider name" pulled in in those spot when the value is not null (blank). If it's null or blank, you'd want to pull in the site name so you don't have to configure it on every site. But I'll leave that up to you. Let me know if you have any questions.

**Comment by Creekridge** [comment]
@tbstevens  - We want to configure it on EVERY site.  The screens/areas that need the field is the verbiage in the Terms & Agreement popup when you submit the application and as a tag in the documents (which I should be able to change) - as stated in my original submission.

**Comment by tbstevens** [comment]
@creekridge - Based on the request, the estimate to move forward with this enhancement is 3-4 hours for setup, dev, testing, and deployment. Please let me know if you would like to move forward with this and we can fast track it to the dev team to hopefully have it ready to be deployed prior to Monday.

**Comment by Creekridge** [comment]
@tbstevens - please proceed.

**Comment by tbstevens** [comment]
@Creekridge - Sounds good. I'm going to close this one out and log as 3 separate issues so they can be tracked separately from one another.
